name: Build and Release

on:
  push:
    tags:
      - 'release*'  # Runs only when a tag like "v1.0" is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change this to your Java version

      - name: Build with Maven
        run: mvn package  # Use 'gradle build' if using Gradle

      - name: Upload JAR as Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar  # Update path if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
